name: Simple Kibot CI/CD Test
on:
  push:
    paths:
    - '**.yaml'
    - '**.kicad_sch'
    - '**.kicad_pcb'
    - '.github/workflows/*.yml'    
  pull_request:
    paths:
      - '**.yaml'    
      - '**.kicad_sch'
      - '**.kicad_pcb'
      - '.github/workflows/*.yml'  
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: INTI-CMNB/KiBot@v2_k9
      with:
        # Required - kibot config file
        config: .kibot/config.kibot.yaml
        # optional - prefix to output defined in config
        dir: output
        # optional - schematic file
        #schema: 'schematic.kicad_sch'
        # optional - PCB design file
        #board: 'pcb.kicad_pcb'
    - name: upload results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: output
        path: output